// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ComDetail: typeof import('./src/components/ComDetail/index.vue')['default']
    ComDialog: typeof import('./src/components/ComDialog/index.vue')['default']
    ComForm: typeof import('./src/components/ComForm/index.vue')['default']
    ComSearch: typeof import('./src/components/ComSearch/index.vue')['default']
    ComTable: typeof import('./src/components/ComTable/index.vue')['default']
    Echart: typeof import('./src/components/Echart/index.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCascader: typeof import('element-ui/lib/cascader')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElCollapseTransition: typeof import('element-ui/lib/transitions/collapse-transition')['default']
    ElColorPicker: typeof import('element-ui/lib/color-picker')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    Ellipsis: typeof import('./src/components/Ellipsis/index.vue')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElRate: typeof import('element-ui/lib/rate')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSlider: typeof import('element-ui/lib/slider')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTimeSelect: typeof import('element-ui/lib/time-select')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElTransfer: typeof import('element-ui/lib/transfer')['default']
    Marquee: typeof import('./src/components/Marquee/index.vue')['default']
    Slot: typeof import('./src/components/ComTable/components/Slot.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TableColumn: typeof import('./src/components/ComTable/components/TableColumn.vue')['default']
  }
}

export { }
